import { AtSign, Check, ChevronRight, LockKeyhole, LogOut, MapPin, Phone, Save, Settings, ShieldCheck, UserRound } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { updateProfile } from '../../services/api';

export default function LogisticsProfilePage() {
    const navigate = useNavigate();
    const stored = JSON.parse(localStorage.getItem('farmdirect_user') || '{}');
    const profileData = stored.profile_data || {};
    const [editing, setEditing] = useState(false);
    const [message, setMessage] = useState('');
    const [error, setError] = useState('');
    const [profile, setProfile] = useState({ full_name: stored.full_name || 'Rahul Kumar', phone: stored.phone || '+91 98765 43210', email: stored.email || 'rahul@farmdirect.ai', address: profileData.address || 'Guntur, Andhra Pradesh', language: profileData.language || 'English, Telugu' });
    const initials = profile.full_name.split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase();
    const fields = [{ label: 'Phone', key: 'phone', icon: Phone, type: 'tel' }, { label: 'Email', key: 'email', icon: AtSign, type: 'email' }, { label: 'Location', key: 'address', icon: MapPin, type: 'text' }, { label: 'Languages', key: 'language', icon: UserRound, type: 'text' }];
    async function save(event) { event.preventDefault(); setMessage(''); setError(''); try { const result = await updateProfile(profile); const nextUser = { ...stored, ...result.user, full_name: result.user?.full_name || profile.full_name, phone: result.user?.phone || profile.phone, email: result.user?.email || profile.email, profile_data: result.user?.profile_data || { ...profileData, address: profile.address, language: profile.language } }; localStorage.setItem('farmdirect_user', JSON.stringify(nextUser)); setEditing(false); setMessage('Profile updated successfully.'); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to update profile'); } }
    function logout() { localStorage.removeItem('farmdirect_token'); localStorage.removeItem('farmdirect_user'); navigate('/login'); }
    return <main className="logistics-profile-page"><div className="logistics-profile-container"><header className="logistics-profile-header"><div><Link className="logistics-feature-back" to="/dashboard/logistics"><ChevronRight size={14} /> Dispatch dashboard</Link><p className="logistics-feature-kicker"><UserRound size={14}/> ACCOUNT PROFILE</p><h1>Profile &amp; Settings</h1><p>Manage your dispatch identity, contact details, and account access.</p></div><button type="button" className="logistics-profile-edit" onClick={() => editing ? save({ preventDefault: () => undefined }) : setEditing(true)}>{editing ? <><Save size={15}/> Save</> : <><Check size={15}/> Edit</>}</button></header>{message && <p className="logistics-feature-notice" role="status"><ShieldCheck size={15}/>{message}</p>}{error && <p className="logistics-feature-error" role="alert">{error}</p>}<section className="logistics-profile-card"><div className="logistics-profile-identity"><div className="logistics-profile-avatar">{initials}</div><div><h2>{profile.full_name}</h2><p>Logistics Provider</p><span><ShieldCheck size={12}/> Verified account</span></div></div><div className="logistics-profile-fields">{fields.map(({ label, key, icon: Icon, type }) => <label key={key}><span><Icon size={13}/> {label}</span>{editing ? <input type={type} value={profile[key]} onChange={(event) => setProfile({ ...profile, [key]: event.target.value })}/> : <strong>{profile[key]}</strong>}</label>)}</div></section><section className="logistics-account-settings"><div className="logistics-account-settings-head"><div><span>ACCOUNT SETTINGS</span><h2>Security and access</h2></div><Settings size={18}/></div><Link to="/logistics/settings"><span><LockKeyhole size={16}/><strong>Change password</strong><small>Update your account password</small></span><ChevronRight size={16}/></Link><button type="button" onClick={logout}><span><LogOut size={16}/><strong>Log out</strong><small>End this dispatch session</small></span><ChevronRight size={16}/></button></section></div></main>;
}
