import { CheckCircle2, CircleDot, Map, Package, Plus, Route, Trash2, Truck, UserRound } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { acceptDelivery, createDriver, createVehicle, deleteDriver, deleteVehicle, getDeliveries, getDrivers, getVehicles, updateDelivery } from '../../services/api';

const nextStatus = { VEHICLE_ASSIGNED: 'PICKED_UP', PICKED_UP: 'IN_TRANSIT', IN_TRANSIT: 'OUT_FOR_DELIVERY', OUT_FOR_DELIVERY: 'DELIVERED' };

export default function LogisticsDashboardPage() {
    const [deliveries, setDeliveries] = useState([]);
    const [vehicles, setVehicles] = useState([]);
    const [drivers, setDrivers] = useState([]);
    const [vehicle, setVehicle] = useState({ registration_number: '', vehicle_type: 'Truck', capacity_kg: 1000 });
    const [driver, setDriver] = useState({ full_name: '', phone: '', license_number: '' });
    const [state, setState] = useState({ error: '', message: '', loading: true });

    async function refresh() {
        const [deliveryResult, vehicleResult, driverResult] = await Promise.all([getDeliveries(), getVehicles(), getDrivers()]);
        setDeliveries(deliveryResult.items || []);
        setVehicles(vehicleResult.items || []);
        setDrivers(driverResult.items || []);
    }
    useEffect(() => { refresh().catch(() => setState({ loading: false, error: 'Unable to load logistics data', message: '' })).finally(() => setState((current) => ({ ...current, loading: false }))); }, []);
    async function submitVehicle(event) { event.preventDefault(); try { await createVehicle(vehicle); setVehicle({ registration_number: '', vehicle_type: 'Truck', capacity_kg: 1000 }); setState({ loading: false, error: '', message: 'Vehicle registered.' }); await refresh(); } catch (error) { setState((current) => ({ ...current, error: error instanceof Error ? error.message : 'Unable to register vehicle' })); } }
    async function submitDriver(event) { event.preventDefault(); try { await createDriver(driver); setDriver({ full_name: '', phone: '', license_number: '' }); setState({ loading: false, error: '', message: 'Driver registered.' }); await refresh(); } catch (error) { setState((current) => ({ ...current, error: error instanceof Error ? error.message : 'Unable to register driver' })); } }
    async function removeVehicle(id) { try { await deleteVehicle(id); setState((current) => ({ ...current, error: '', message: 'Vehicle removed.' })); await refresh(); } catch (error) { setState((current) => ({ ...current, error: error instanceof Error ? error.message : 'Unable to remove vehicle' })); } }
    async function removeDriver(id) { try { await deleteDriver(id); setState((current) => ({ ...current, error: '', message: 'Driver removed.' })); await refresh(); } catch (error) { setState((current) => ({ ...current, error: error instanceof Error ? error.message : 'Unable to remove driver' })); } }
    async function advance(delivery) {
        try {
            if (delivery.status === 'AVAILABLE') await acceptDelivery(delivery.id);
            else if (delivery.status === 'ACCEPTED') {
                const availableVehicle = vehicles.find((item) => item.is_available);
                const availableDriver = drivers.find((item) => item.is_available);
                if (!availableVehicle || !availableDriver) throw new Error('Register an available vehicle and driver first');
                await updateDelivery(delivery.id, 'VEHICLE_ASSIGNED', availableVehicle.id, availableDriver.id);
            } else if (nextStatus[delivery.status]) await updateDelivery(delivery.id, nextStatus[delivery.status]);
            setState((current) => ({ ...current, error: '', message: 'Delivery updated.' }));
            await refresh();
        } catch (error) { setState((current) => ({ ...current, error: error instanceof Error ? error.message : 'Unable to update delivery' })); }
    }
    const activeDeliveries = useMemo(() => deliveries.filter((item) => item.status !== 'DELIVERED'), [deliveries]);
    return <main className="logistics-page min-h-screen p-6 text-white sm:p-8"><div className="container">
            <div className="flex flex-wrap gap-4"><Link className="text-sm text-emerald-200" to="/profile">Profile</Link><Link className="inline-flex items-center gap-1 text-sm text-emerald-200" to="/logistics/route-estimate"><Map size={14}/> Route estimate</Link></div>
            <section className="logistics-hero mt-8"><div><p className="eyebrow inline-flex items-center gap-2 rounded-full px-3 py-1 text-xs font-bold uppercase tracking-[0.2em]"><Truck size={14}/> Logistics operations</p><h1 className="mt-4 text-4xl font-black md:text-6xl">Move every order with confidence.</h1><p className="mt-4 max-w-2xl text-emerald-50/70">Coordinate vehicles, drivers, and delivery status from one operational view.</p></div><div className="logistics-hero-icon"><Route size={38}/></div></section>
            {state.message && <p className="mt-4 text-emerald-200" role="status">{state.message}</p>}{state.error && <p className="mt-4 text-rose-300" role="alert">{state.error}</p>}
            <div className="logistics-kpis mt-8 grid gap-4 sm:grid-cols-3"><div className="card"><Truck size={18}/><strong>{vehicles.length}</strong><span>Fleet vehicles</span></div><div className="card"><UserRound size={18}/><strong>{drivers.length}</strong><span>Registered drivers</span></div><div className="card"><Package size={18}/><strong>{activeDeliveries.length}</strong><span>Active deliveries</span></div></div>
            <div className="mt-8 grid gap-6 xl:grid-cols-[0.75fr_1.25fr]"><div className="space-y-6"><form className="card operations-form p-6" onSubmit={submitVehicle}><div className="flex items-center gap-3"><span className="operation-icon"><Truck size={18}/></span><div><h2 className="text-xl font-bold">Register vehicle</h2><p className="text-sm text-emerald-50/60">Add capacity to the dispatch desk.</p></div></div><input placeholder="Registration number" value={vehicle.registration_number} onChange={(event) => setVehicle({ ...vehicle, registration_number: event.target.value })} required/><input placeholder="Vehicle type" value={vehicle.vehicle_type} onChange={(event) => setVehicle({ ...vehicle, vehicle_type: event.target.value })} required/><input type="number" min="1" placeholder="Capacity in kg" value={vehicle.capacity_kg} onChange={(event) => setVehicle({ ...vehicle, capacity_kg: Number(event.target.value) })} required/><button className="btn-primary" type="submit"><Plus size={16}/> Add vehicle</button></form><form className="card operations-form p-6" onSubmit={submitDriver}><div className="flex items-center gap-3"><span className="operation-icon"><UserRound size={18}/></span><div><h2 className="text-xl font-bold">Register driver</h2><p className="text-sm text-emerald-50/60">Keep the route roster current.</p></div></div><input placeholder="Full name" value={driver.full_name} onChange={(event) => setDriver({ ...driver, full_name: event.target.value })} required/><input placeholder="Phone" value={driver.phone} onChange={(event) => setDriver({ ...driver, phone: event.target.value })} required/><input placeholder="License number" value={driver.license_number} onChange={(event) => setDriver({ ...driver, license_number: event.target.value })} required/><button className="btn-primary" type="submit"><Plus size={16}/> Add driver</button></form></div>
            <div className="space-y-6"><section className="card fleet-panel p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-200/70">Dispatch resources</p><h2 className="mt-2 text-2xl font-bold">Fleet and drivers</h2></div><CircleDot className="text-emerald-300" size={22}/></div><div className="mt-5 grid gap-3 md:grid-cols-2"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.14em] text-emerald-200/60">Vehicles</p>{vehicles.map((item) => <div className="resource-row" key={item.id}><span><Truck size={15}/> {item.registration_number}</span><button type="button" aria-label={`Remove ${item.registration_number}`} onClick={() => removeVehicle(item.id)}><Trash2 size={14}/></button></div>)}{vehicles.length === 0 && <p className="text-sm text-emerald-50/60">No vehicles registered.</p>}</div><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.14em] text-emerald-200/60">Drivers</p>{drivers.map((item) => <div className="resource-row" key={item.id}><span><UserRound size={15}/> {item.full_name}</span><button type="button" aria-label={`Remove ${item.full_name}`} onClick={() => removeDriver(item.id)}><Trash2 size={14}/></button></div>)}{drivers.length === 0 && <p className="text-sm text-emerald-50/60">No drivers registered.</p>}</div></div></section><section><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-200/70">Live queue</p><h2 className="mt-2 text-2xl font-bold">Delivery operations</h2></div><span className="status-chip"><CheckCircle2 size={13}/> {activeDeliveries.length} active</span></div>{deliveries.map((delivery) => <article className="delivery-card card" key={delivery.id}><div className="delivery-route"><span className="delivery-pin"/><div><strong>Order #{delivery.order_id}</strong><p>{delivery.pickup_location} <b>→</b> {delivery.destination}</p></div></div><div className="delivery-action"><span className="status-chip">{delivery.status}</span>{delivery.status !== 'DELIVERED' && <button className="btn-secondary" type="button" onClick={() => advance(delivery)}>{delivery.status === 'AVAILABLE' ? 'Accept delivery' : 'Advance status'}</button>}</div></article>)}{deliveries.length === 0 && <div className="empty-state card"><Package size={32}/><h2>No deliveries available</h2><p>New logistics requests will appear here.</p></div>}</section></div></div>
        </div></main>;
}
