import { ArrowRight, CheckCircle2, Package } from 'lucide-react';
import { Link } from 'react-router-dom';
import { getOrders } from '../../services/api';
export default function OrdersPage() {
    const [orders, setOrders] = useState([]);
    const [state, setState] = useState({ loading: true, error: '' });
    useEffect(() => { getOrders().then((result) => setOrders(result.items || [])).catch((error) => setState({ loading: false, error: error instanceof Error ? error.message : 'Unable to load orders' })).finally(() => setState((current) => ({ ...current, loading: false }))); }, []);
    return <main className="orders-page min-h-screen p-6 text-white sm:p-8"><div className="container max-w-4xl"><Link className="inline-flex items-center gap-2 text-sm text-emerald-200" to="/dashboard/consumer"><ArrowRight className="rotate-180" size={15}/> Dashboard</Link><div className="mt-8 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-200/70">Commerce history</p><h1 className="mt-3 text-4xl font-black md:text-5xl">Your orders</h1></div><Package className="text-emerald-300" size={30}/></div>{state.error && <p className="mt-5 text-rose-300" role="alert">{state.error}</p>}{state.loading ? <div className="card mt-6 h-36 animate-pulse"/> : <div className="mt-6 space-y-3">{orders.map((order) => <article className="card order-card p-5" key={order.id}><Link className="block" to={`/orders/${order.id}/tracking`}><div className="flex justify-between gap-4"><span className="font-semibold">Order #{order.id}</span><span className="status-chip"><CheckCircle2 size={13}/> {order.status}</span></div><p className="mt-2 text-sm text-emerald-50/65">₹{Number(order.total_amount).toFixed(2)}{order.created_at ? ` · ${new Date(order.created_at).toLocaleDateString()}` : ''}</p></Link>{order.items?.map((item) => <Link className="mt-3 inline-block text-sm text-emerald-200 underline" to={`/review?product=${item.product_id}&order=${order.id}`} key={item.product_id}>Review {item.product_name}</Link>)}</article>)}{orders.length === 0 && <div className="empty-state card"><Package size={32}/><h2>No orders yet</h2><p>Completed purchases will appear here.</p><Link className="btn-secondary" to="/marketplace">Explore marketplace</Link></div>}</div>}</div></main>;
}
