import { CheckCircle2, CreditCard, XCircle } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { getPayments } from '../../services/api';
export default function PaymentsPage() {
    const [payments, setPayments] = useState([]);
    const [state, setState] = useState({ loading: true, error: '' });
    useEffect(() => { getPayments().then((result) => setPayments(result.items || [])).catch((error) => setState({ loading: false, error: error instanceof Error ? error.message : 'Unable to load payments' })).finally(() => setState((current) => ({ ...current, loading: false }))); }, []);
    return <main className="payments-page min-h-screen p-6 text-white sm:p-8"><div className="container max-w-4xl"><Link className="text-sm text-emerald-200" to="/dashboard/consumer">Dashboard</Link><div className="mt-8 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-200/70">Money trail</p><h1 className="mt-3 text-4xl font-black">Payment history</h1></div><CreditCard className="text-emerald-300" size={30}/></div>{state.error && <p className="mt-5 text-rose-300" role="alert">{state.error}</p>}{state.loading ? <div className="card mt-6 h-36 animate-pulse"/> : <div className="mt-6 space-y-3">{payments.map((payment) => { const succeeded = payment.status === 'SUCCEEDED'; return <article className="card flex flex-wrap items-center justify-between gap-4 p-5" key={payment.id}><div className="flex items-center gap-3"><span className={`payment-icon ${succeeded ? 'payment-success' : 'payment-failed'}`}>{succeeded ? <CheckCircle2 size={18}/> : <XCircle size={18}/>}</span><div><h2 className="font-semibold">Order #{payment.order_id}</h2><p className="mt-1 text-sm text-emerald-50/65">{payment.transaction_reference || 'Transaction pending'} · {payment.provider || 'Payment gateway'}</p></div></div><div className="text-right"><p className="font-bold text-emerald-200">₹{Number(payment.amount).toFixed(2)}</p><p className="text-sm text-emerald-50/65">{payment.status}</p></div></article>; })}{payments.length === 0 && <div className="empty-state card"><CreditCard size={32}/><h2>No payments yet</h2><p>Your payment records will appear after checkout.</p></div>}</div>}</div></main>;
}
