import { ArrowLeft, ArrowUpRight, CheckCircle2, CreditCard, ShieldCheck, XCircle } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { getPayments } from '../../services/api';
export default function PaymentsPage() {
    const [payments, setPayments] = useState([]);
    const [state, setState] = useState({ loading: true, error: '' });
    useEffect(() => { getPayments().then((result) => setPayments(result.items || [])).catch((error) => setState({ loading: false, error: error instanceof Error ? error.message : 'Unable to load payments' })).finally(() => setState((current) => ({ ...current, loading: false }))); }, []);
    const user = JSON.parse(localStorage.getItem('farmdirect_user') || '{}');
    const dashboardPath = user.role === 'bulk_buyer' ? '/dashboard/bulk-buyer' : '/dashboard/consumer';
    const totalPaid = payments.filter((payment) => payment.status === 'SUCCEEDED').reduce((total, payment) => total + Number(payment.amount || 0), 0);
    return <main className="payments-page"><div className="payments-container"><Link className="payments-back-link" to={dashboardPath}><ArrowLeft size={15}/> Back to workspace</Link><header className="payments-hero"><div><p className="payments-kicker"><ShieldCheck size={14}/> Money trail</p><h1>Every payment, accounted for.</h1><p>Review procurement spend, transaction references, and payment status in one trusted ledger.</p></div><div className="payments-hero-card"><CreditCard size={25}/><span>SETTLED VALUE</span><strong>₹{totalPaid.toLocaleString('en-IN', { minimumFractionDigits: 2 })}</strong></div></header>{state.error && <p className="payments-error" role="alert">{state.error}</p>}{state.loading ? <div className="payments-loading"/> : <><section className="payments-summary"><div><span>Transactions</span><strong>{payments.length}</strong><small>recorded payments</small></div><div><span>Successful value</span><strong>₹{totalPaid.toLocaleString('en-IN', { maximumFractionDigits: 0 })}</strong><small>settled through FarmDirect</small></div><div><span>Ledger status</span><strong>Clear</strong><small>all records available</small></div></section><div className="payments-list">{payments.map((payment) => { const succeeded = payment.status === 'SUCCEEDED'; return <article className={`payment-card ${succeeded ? 'is-success' : 'is-failed'}`} key={payment.id}><div className="payment-card-icon">{succeeded ? <CheckCircle2 size={19}/> : <XCircle size={19}/>}</div><div className="payment-card-main"><span className="payment-reference">{payment.transaction_reference || 'TRANSACTION PENDING'}</span><h2>Order #{payment.order_id}</h2><p>{payment.provider || 'Payment gateway'} · {payment.created_at ? new Date(payment.created_at).toLocaleDateString() : 'Date unavailable'}</p></div><div className="payment-card-total"><strong>₹{Number(payment.amount || 0).toFixed(2)}</strong><span>{payment.status}</span><ArrowUpRight size={16}/></div></article>; })}{payments.length === 0 && <div className="payments-empty"><CreditCard size={30}/><div><span className="payments-kicker">No ledger entries</span><h2>Your payment history is ready.</h2><p>Payment records will appear after your first checkout.</p><Link to="/marketplace">Browse marketplace <ArrowUpRight size={15}/></Link></div></div>}</div></>}</div></main>;
}
