import { Check, Circle, MapPin, Package, Truck } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { getTracking } from '../../services/api';
export default function TrackingPage() {
    const { orderId } = useParams();
    const [delivery, setDelivery] = useState(null);
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(true);
    useEffect(() => { if (orderId) getTracking(Number(orderId)).then((result) => setDelivery(result.delivery)).catch((requestError) => setError(requestError instanceof Error ? requestError.message : 'Tracking unavailable')).finally(() => setLoading(false)); }, [orderId]);
    return <main className="tracking-page min-h-screen p-6 text-white sm:p-8"><div className="container max-w-4xl"><Link className="text-sm text-emerald-200" to="/orders">Orders</Link><div className="tracking-heading mt-8"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-200/70">Live fulfilment</p><h1 className="mt-3 text-4xl font-black md:text-5xl">Track order #{orderId}</h1></div>{delivery && <span className="status-chip">{delivery.status}</span>}</div>{error && <div className="empty-state card mt-6" role="alert"><Package size={30}/><h2>Tracking is not available yet</h2><p>{error}</p></div>}{loading && <div className="card mt-6 h-64 animate-pulse"/>}{delivery && <div className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_0.9fr]"><div className="tracking-map card"><div className="tracking-route-line"/><div className="tracking-stop tracking-stop-start"><MapPin size={20}/><span>{delivery.pickup_location}</span></div><div className="tracking-stop tracking-stop-end"><Truck size={20}/><span>{delivery.destination}</span></div><div className="tracking-route-center"><Package size={25}/></div></div><section className="card p-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-200/70">Journey timeline</p><div className="tracking-timeline mt-6">{delivery.events.map((event, index) => <div className="tracking-event" key={event.id}><span className="tracking-event-icon">{index === delivery.events.length - 1 ? <Check size={14}/> : <Circle size={10}/>}</span><div><p className="font-bold">{event.status}</p><p className="mt-1 text-sm text-emerald-50/65">{event.note || 'Status updated'}</p></div></div>)}</div></section></div>}</div></main>;
}
