import { Bell, Boxes, CircleUserRound, ChevronDown, Heart, LayoutDashboard, LogOut, Map, Menu, Package, Search, Settings, ShoppingCart, Sparkles, Tractor, Truck, Users, Wallet, Wheat, X } from 'lucide-react';
import { useState } from 'react';
import { Link, Outlet, useLocation, useNavigate } from 'react-router-dom';
export default function DashboardShell() {
    const navigate = useNavigate();
    const location = useLocation();
    const [open, setOpen] = useState(false);
    const [search, setSearch] = useState('');
    const user = JSON.parse(localStorage.getItem('farmdirect_user') || '{}');
    const role = user.role || 'consumer';
    const roleLabels = { consumer: 'Buyer workspace', bulk_buyer: 'Bulk buyer workspace', farmer: 'Farm workspace', admin: 'Control room', logistics_provider: 'Dispatch workspace', fpo: 'FPO workspace', field_assistant: 'Field workspace' };
    const links = role === 'farmer' ? [['/dashboard/farmer', 'Overview', LayoutDashboard], ['/profile', 'My Profile', CircleUserRound], ['/farmer/farm', 'My Farm', Tractor], ['/farmer/products', 'My Products', Wheat], ['/farmer/inventory', 'Inventory', Boxes], ['/farmer/orders', 'Orders', Package], ['/farmer/earnings', 'Sales & Earnings', Wallet], ['/farmer/insights', 'AI Insights', Sparkles], ['/farmer/notifications', 'Notifications', Bell], ['/farmer/tracking', 'Delivery Tracking', Truck], ['/farmer/settings', 'Settings', Settings]] : role === 'admin' ? [['/dashboard/admin', 'Dashboard', LayoutDashboard], ['/admin/users', 'Users', Users], ['/admin/products', 'Products', Boxes], ['/admin/orders', 'Orders', Package]] : role === 'logistics_provider' ? [['/dashboard/logistics', 'Operations', Truck], ['/logistics/route-estimate', 'Routes', Map]] : role === 'consumer' || role === 'bulk_buyer' ? [[`/dashboard/${role === 'bulk_buyer' ? 'bulk-buyer' : 'consumer'}`, 'Home', LayoutDashboard], ['/marketplace', 'Marketplace', ShoppingCart], ['/cart', 'Cart', ShoppingCart], ['/orders', 'Orders', Package], ['/tracking', 'Tracking', Truck], ['/wishlist', 'Wishlist', Heart], ['/payments', 'Payments', Wallet], ['/notifications', 'Notifications', Bell], ['/reviews', 'Reviews', Sparkles], ['/profile', 'Profile', CircleUserRound]] : role === 'fpo' ? [['/dashboard/fpo', 'Dashboard', LayoutDashboard], ['/fpo/members', 'Members', Users], ['/fpo/farmers', 'Farmers', Tractor], ['/fpo/inventory', 'Inventory', Boxes], ['/fpo/aggregations', 'Aggregation', Wheat], ['/fpo/marketplace', 'Marketplace', ShoppingCart], ['/fpo/bulk-buyers', 'Bulk Buyers', Users], ['/fpo/logistics', 'Logistics', Truck], ['/fpo/analytics', 'Analytics', Sparkles], ['/fpo/notifications', 'Notifications', Bell], ['/fpo/settings', 'Settings', Settings]] : [[`/dashboard/${role === 'field_assistant' ? 'field-assistant' : role}`, 'Workspace', Tractor]];
    function isNavActive(path) {
        const pathname = location.pathname;
        if (pathname === path) return true;
        if (path === '/orders') return pathname === '/orders' || (pathname.startsWith('/orders/') && !pathname.includes('/tracking'));
        if (path === '/tracking') return pathname === '/tracking' || pathname.startsWith('/tracking/') || pathname.includes('/tracking');
        if (path === '/reviews') return pathname === '/reviews' || pathname === '/review' || pathname.startsWith('/reviews/') || pathname.startsWith('/review/');
        if (path === '/profile') return pathname === '/profile' || pathname.startsWith('/profile/');
        if (path.startsWith('/fpo/')) return pathname === path || pathname.startsWith(path + '/');
        return path !== links[0][0] && pathname.startsWith(path + '/');
    }
    function logout() { localStorage.removeItem('farmdirect_token'); localStorage.removeItem('farmdirect_user'); navigate('/login'); }
    function submitSearch(event) { event.preventDefault(); if (role === 'consumer' || role === 'bulk_buyer') navigate(`/marketplace${search.trim() ? `?search=${encodeURIComponent(search.trim())}` : ''}`); if (role === 'fpo') navigate(`/fpo/marketplace${search.trim() ? `?search=${encodeURIComponent(search.trim())}` : ''}`); }
    return <div className={`dashboard-shell role-${role}`}><aside className={`dashboard-sidebar ${open ? 'is-open' : ''}`}><Link className="dashboard-brand" to={links[0][0]}><span className="dashboard-brand-mark">FD</span><span className="dashboard-brand-copy"><span className="dashboard-brand-name"><strong>FarmDirect</strong><em>AI</em></span><small>From Our Farms to You</small></span></Link><nav className="dashboard-nav">{links.map(([path, label, Icon]) => <Link className={`dashboard-link ${isNavActive(path) ? 'is-active' : ''}`} onClick={() => setOpen(false)} to={path} key={`${path}-${label}`}><Icon size={15}/><span>{label}</span></Link>)}</nav><button className="dashboard-logout" type="button" onClick={logout}><LogOut size={15}/><span>Log out</span></button></aside><div className="dashboard-workspace"><header className="dashboard-header"><div className="dashboard-toolbar"><button className="dashboard-menu" type="button" aria-label="Toggle navigation" onClick={() => setOpen(!open)}>{open ? <X size={20}/> : <Menu size={20}/>}</button><form className="dashboard-search" onSubmit={submitSearch}><Search size={15}/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={role === 'farmer' ? 'Search for my farm...' : 'Search produce, orders...'} aria-label="Search workspace"/></form><div className="dashboard-toolbar-actions"><button className="dashboard-bell" type="button" aria-label="Notifications" onClick={() => navigate(role === 'farmer' ? '/farmer/notifications' : '/notifications')}><Bell size={17}/><i/></button><Link className="dashboard-user-menu" to="/profile"><span className="dashboard-user-avatar">{(user.full_name || 'User').slice(0, 1).toUpperCase()}</span><span><strong>{user.full_name || 'User'}</strong><small>{role === 'farmer' ? 'Farmer' : roleLabels[role] || 'Workspace'}</small></span><ChevronDown size={14}/></Link></div></div></header><Outlet /></div></div>;
}
