import { Bell, Boxes, CircleUserRound, LayoutDashboard, LogOut, Map, Menu, Package, ShoppingCart, Tractor, Truck, Users, Wallet, Wheat, X } from 'lucide-react';
import { useState } from 'react';
import { Link, Outlet, useNavigate } from 'react-router-dom';
export default function DashboardShell() {
    const navigate = useNavigate();
    const [open, setOpen] = useState(false);
    const user = JSON.parse(localStorage.getItem('farmdirect_user') || '{}');
    const role = user.role || 'consumer';
    const links = role === 'farmer' ? [['/dashboard/farmer', 'Dashboard', LayoutDashboard], ['/farmer/products', 'Products', Wheat], ['/farmer/orders', 'Orders', Package]] : role === 'admin' ? [['/dashboard/admin', 'Dashboard', LayoutDashboard], ['/admin/users', 'Users', Users], ['/admin/products', 'Products', Boxes], ['/admin/orders', 'Orders', Package]] : role === 'logistics_provider' ? [['/dashboard/logistics', 'Operations', Truck], ['/logistics/route-estimate', 'Routes', Map]] : role === 'consumer' || role === 'bulk_buyer' ? [['/dashboard/consumer', 'Dashboard', LayoutDashboard], ['/marketplace', 'Marketplace', ShoppingCart], ['/orders', 'Orders', Package], ['/payments', 'Payments', Wallet], ['/notifications', 'Notifications', Bell]] : [[`/dashboard/${role === 'field_assistant' ? 'field-assistant' : role}`, 'Workspace', Tractor]];
    function logout() { localStorage.removeItem('farmdirect_token'); localStorage.removeItem('farmdirect_user'); navigate('/login'); }
    return <><header className="dashboard-header sticky top-0 z-20 px-4 py-3 md:px-6"><div className="container flex items-center justify-between"><Link className="dashboard-brand" to={links[0][0]}><span className="dashboard-brand-mark">FD</span><span>FarmDirect <em>AI</em></span></Link><button className="dashboard-menu" type="button" aria-label="Toggle navigation" onClick={() => setOpen(!open)}>{open ? <X size={20}/> : <Menu size={20}/>}</button><nav className={`${open ? 'dashboard-nav-open' : ''} dashboard-nav`}>{links.map(([path, label, Icon]) => <Link className="dashboard-link" onClick={() => setOpen(false)} to={path} key={path}><Icon size={16}/><span>{label}</span></Link>)}<Link className="dashboard-link dashboard-profile-link" onClick={() => setOpen(false)} to="/profile"><CircleUserRound size={16}/><span>{user.full_name || 'Profile'}</span></Link><button className="dashboard-logout" type="button" onClick={logout}><LogOut size={16}/><span>Log out</span></button></nav></div></header><Outlet /></>;
}
